version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3002:3002"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root          # Gunakan 'root' sebagai pengguna
      DB_PASS: root          # Password root yang sama seperti MYSQL_ROOT_PASSWORD
      DB_NAME: web_chat      # Nama database yang diinginkan

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: web_chat        # Nama database yang akan dibuat
      MYSQL_ROOT_PASSWORD: root       # Password untuk root user
    ports:
      - "3307:3306"  # Ganti ini jika port 3306 sudah digunakan di host
